import { fmtTokens } from "@kotys/contracts";
import { fmtInt } from "./format";

function StatCard({
  label,
  value,
  hint,
}: {
  label: string;
  value: string;
  hint?: string;
}) {
  return (
    <div className="rounded-xl border border-border bg-surface p-4">
      <div className="text-xs text-text-muted">{label}</div>
      <div className="mt-1 text-2xl font-semibold text-text">{value}</div>
      {hint && <div className="mt-1 text-xs text-text-muted">{hint}</div>}
    </div>
  );
}

export function StatCards({
  messages,
  userMessages,
  evalTokens,
  chats,
  toolCalls,
  distinctTools,
}: {
  messages: number;
  userMessages: number;
  evalTokens: number;
  chats: number;
  toolCalls: number;
  distinctTools: number;
}) {
  const cards = [
    {
      label: "Messages",
      value: fmtInt(messages),
      hint: `${fmtInt(userMessages)} from you`,
    },
    {
      label: "Output tokens",
      value: fmtTokens(evalTokens),
      hint: "generated by models",
    },
    { label: "Chats", value: fmtInt(chats) },
    {
      label: "Tool calls",
      value: fmtInt(toolCalls),
      hint: `${distinctTools} distinct`,
    },
  ];

  return (
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
      {cards.map((c) => (
        <StatCard key={c.label} {...c} />
      ))}
    </div>
  );
}
